### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by ultrahacker678** [KnownBlackHat/cdn-web-app#1]
Not issue, i just want to get some your contact, telegramm, facebook, mb other messager, if you havent plz give your mail

**Comment by KnownBlackHat** [comment]
> Not issue, i just want to get some your contact, telegramm, facebook, mb other messager, if you havent plz give your mail

Contacts Info:
Gmail: knownblackhat@gmail.com
Discord: https://discord.gg/2uYRT2KmBU
Instagram: https://www.instagram.com/known_black_hat/
